sudo: false
dist: xenial
services: docker
language: python
matrix:
  include:
  - python: '3.7'
    env: LTD_SKIP_UPLOAD=false DEPLOY_DOCKER_IMAGE=true PYPI_DEPLOY=true
install:
- pip install .
- pip install ltd-conveyor==0.5.0a1
script:
- python setup.py test
- cd docs && make html && cd ../
- make docker
after_success:
- ltd upload --product kafka-connect-manager --travis --dir docs/_build/html
- make travis-docker-deploy
env:
  global:
  - DEPLOY_DOCKER_IMAGE=false
  - LTD_SKIP_UPLOAD=true
  # LSST the Docs credentials
  - secure: ckQRzpqPi72cdGXqXRaJ+rEXWsXoEBrQ3c0e/N3LhhTUi1FrtqZLRhg4QBDj555luzSaALhCbOwpKtunuSxrJIPwTilV7n//mLnxPay5Lgf0wXmPNH10uzRGkg5V/JFi0hLp5+oXB6pJGpENpeS6ZGd6pFafMemEXwAxwr66mPg5h1wBD2QBByakrvn+rc4jo6t7SxdaawPcYPU/n1qSRSXmcwNGXYQUM89xfMXPTO0pDzNBIgEpXSuO+4AaxET2Zqt+UvVpNzKTpEIK/5ztknw+0syXfRIT0FKH1U2reSmIjKPMINj6qH6ECWvHO5jRtIaFy52dcg4LW/W6HgXFMK4Ik3UOEjjZNxJbZcVPFBnYc4pAehqcz9pXVyrc4ppCrMmuPQ0L6uJT93e2Yg9EYrLnxGslnw5vWqOfSsfmxwugbkB21JAmifTOz3rpeXcIhpM8N/BTU/Xu+oaIIcshbaZZ94VYqHcBdNBRNKBi0PL/RGUiHmNQEVM+EWXBbHCwTWML/D0JuSjwRKrYMBJSIiFJ9a/bm52wPGLvH6GQXMEOyWXMTbRpuoZ3Mpzl9ASFDa+bf2wf+97kbrG2606WKF8iwCm5mPo/O2aTPeH+j7HlqGAXmTN/Hm1Q2ke9AEJdmXoCW/egpFmsIx8Oe/jVQs1LUEW0Xx1uV7dRzP90v1c=
  # DockerHub credentials
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: afausti
  password:
    secure: SGSjix4Yodcr9sdHvskbBRWPslu0OSv+6yFOvpO2BvnvD+NrreIyTa6M5U8vgvOee0+aJf7POjfTzHeRtvIj/jIl80oRzuAE7ID71qZvP8LA67JsaDQAZtU9yszMXF9MKrFZ1yqbr/urttTmjiILMqrXl0nUK3anG6KwI1C2C0N0bB0P+/QhMQs9MBFLrLwowuP/GmNzBsozCpoApspF4PqBdNvuhWYNlrsrHeLY9aW8pU1WYuiHaPjzjbnnp+/rK/QJU5plSaqH2e9rNtSgm4a+2DwSTKDKY7jvr0HF+S8SbJHwkt8kZBDvqmIWDUdMdM7/ScSt1VCxh7K0on5NhxLEafjON2MJ706WA7fcIdwnl1BKVa0GkGyXmms414sTsagvrltHZSfiOVjx0mWJnmhH8lCj5Q5KGp+iHvPZvEH+j7VKSMIIzfHM7jm0xO6yRnJ5/o/nPCSkkA7QXvzqjRAlD4HL3P3u7ONvG2wSvqIMFQxZXiBeXWieED5NnzBwOSdB7qrtRxiO8LNECkSiYWWY0wD5OestbIZ9Vm+rtGirSK9qBI8kQ4JMusIjkp8AIZxY1EeJM7tjbthbxpxdMN/W8+bj/ysRABmFD/PIQ2lX3TrCX/JMY7Pgncaas7TZMdNUfjJvAKVWzJokdTTbUS0golleoLHxUYx+ww6CoG0=
  on:
    tags: true
    repo: lsst-sqre/kafka-connect-manager
    python: 3.7
    condition: "$PYPI_DEPLOY = true"
