---
version: '3'
services:


  zookeeper-src:
    image: confluentinc/cp-zookeeper:5.5.2
    hostname: zookeeper-src
    container_name: zookeeper-src
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-src:
    image: confluentinc/cp-enterprise-kafka:5.5.2
    hostname: broker-src
    container_name: broker-src
    depends_on:
      - zookeeper-src
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-src:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-src:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8082


  schema-registry-src:
    image: confluentinc/cp-schema-registry:5.5.2
    hostname: schema-registry-src
    container_name: schema-registry-src
    depends_on:
      - broker-src
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-src
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-src:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082

